### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by michimon-k** [michimon-k/chat-space#11]
#ipアドレス
13.112.117.152

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・アイコンとユーザー名の周りの背景のみ、色が異なる
[![Screenshot from Gyazo](https://gyazo.com/6941b76df279db0c068959b976bae9eb/raw)](https://gyazo.com/6941b76df279db0c068959b976bae9eb)

修正完了次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by michimon-k** [comment]
背景色修正しました

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
